// Code generated by entc, DO NOT EDIT.

package aircraft

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the aircraft type in the database.
	Label = "aircraft"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "aircraft_id"
	// FieldCompanyID holds the string denoting the company_id field in the database.
	FieldCompanyID = "company_id"
	// FieldCurrentFlightHours holds the string denoting the current_flight_hours field in the database.
	FieldCurrentFlightHours = "current_flight_hours"
	// FieldCurrentCycles holds the string denoting the current_cycles field in the database.
	FieldCurrentCycles = "current_cycles"
	// FieldAircraftRegistration holds the string denoting the aircraft_registration field in the database.
	FieldAircraftRegistration = "aircraft_registration"
	// FieldBaseAirportCode holds the string denoting the base_airport_code field in the database.
	FieldBaseAirportCode = "base_airport_code"
	// FieldManufacturer holds the string denoting the manufacturer field in the database.
	FieldManufacturer = "manufacturer"
	// FieldManufacturerDesignator holds the string denoting the manufacturer_designator field in the database.
	FieldManufacturerDesignator = "manufacturer_designator"
	// FieldCommonDesignation holds the string denoting the common_designation field in the database.
	FieldCommonDesignation = "common_designation"
	// FieldCommonName holds the string denoting the common_name field in the database.
	FieldCommonName = "common_name"
	// FieldPilotsRequiredToFly holds the string denoting the pilots_required_to_fly field in the database.
	FieldPilotsRequiredToFly = "pilots_required_to_fly"
	// FieldDefaultValues holds the string denoting the default_values field in the database.
	FieldDefaultValues = "default_values"
	// FieldMaximumValues holds the string denoting the maximum_values field in the database.
	FieldMaximumValues = "maximum_values"
	// FieldCurrentLandings holds the string denoting the current_landings field in the database.
	FieldCurrentLandings = "current_landings"
	// FieldFuelDetails holds the string denoting the fuel_details field in the database.
	FieldFuelDetails = "fuel_details"
	// FieldOilDetails holds the string denoting the oil_details field in the database.
	FieldOilDetails = "oil_details"
	// Table holds the table name of the aircraft in the database.
	Table = "aircrafts"
)

// Columns holds all SQL columns for aircraft fields.
var Columns = []string{
	FieldID,
	FieldCompanyID,
	FieldCurrentFlightHours,
	FieldCurrentCycles,
	FieldAircraftRegistration,
	FieldBaseAirportCode,
	FieldManufacturer,
	FieldManufacturerDesignator,
	FieldCommonDesignation,
	FieldCommonName,
	FieldPilotsRequiredToFly,
	FieldDefaultValues,
	FieldMaximumValues,
	FieldCurrentLandings,
	FieldFuelDetails,
	FieldOilDetails,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCompanyID holds the default value on creation for the "company_id" field.
	DefaultCompanyID func() uuid.UUID
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
