// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AircraftsColumns holds the columns for the "aircrafts" table.
	AircraftsColumns = []*schema.Column{
		{Name: "aircraft_id", Type: field.TypeUUID, Unique: true},
		{Name: "company_id", Type: field.TypeUUID},
		{Name: "current_flight_hours", Type: field.TypeFloat32, Nullable: true},
		{Name: "current_cycles", Type: field.TypeInt, Nullable: true},
		{Name: "aircraft_registration", Type: field.TypeString, Nullable: true},
		{Name: "base_airport_code", Type: field.TypeString, Nullable: true},
		{Name: "manufacturer", Type: field.TypeString, Nullable: true},
		{Name: "manufacturer_designator", Type: field.TypeString, Nullable: true},
		{Name: "common_designation", Type: field.TypeString, Nullable: true},
		{Name: "common_name", Type: field.TypeString, Nullable: true},
		{Name: "pilots_required_to_fly", Type: field.TypeInt, Nullable: true},
		{Name: "default_values", Type: field.TypeString, Nullable: true},
		{Name: "maximum_values", Type: field.TypeString, Nullable: true},
		{Name: "current_landings", Type: field.TypeInt, Nullable: true},
		{Name: "fuel_details", Type: field.TypeString, Nullable: true},
		{Name: "oil_details", Type: field.TypeString, Nullable: true},
	}
	// AircraftsTable holds the schema information for the "aircrafts" table.
	AircraftsTable = &schema.Table{
		Name:       "aircrafts",
		Columns:    AircraftsColumns,
		PrimaryKey: []*schema.Column{AircraftsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "aircraft_current_flight_hours",
				Unique:  false,
				Columns: []*schema.Column{AircraftsColumns[2]},
			},
			{
				Name:    "aircraft_aircraft_registration",
				Unique:  false,
				Columns: []*schema.Column{AircraftsColumns[4]},
			},
			{
				Name:    "aircraft_common_designation",
				Unique:  false,
				Columns: []*schema.Column{AircraftsColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AircraftsTable,
	}
)

func init() {
}
