// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"enttest/ent/migrate"

	"enttest/ent/aircraft"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Aircraft is the client for interacting with the Aircraft builders.
	Aircraft *AircraftClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Aircraft = NewAircraftClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Aircraft: NewAircraftClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:   cfg,
		Aircraft: NewAircraftClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Aircraft.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Aircraft.Use(hooks...)
}

// AircraftClient is a client for the Aircraft schema.
type AircraftClient struct {
	config
}

// NewAircraftClient returns a client for the Aircraft from the given config.
func NewAircraftClient(c config) *AircraftClient {
	return &AircraftClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `aircraft.Hooks(f(g(h())))`.
func (c *AircraftClient) Use(hooks ...Hook) {
	c.hooks.Aircraft = append(c.hooks.Aircraft, hooks...)
}

// Create returns a create builder for Aircraft.
func (c *AircraftClient) Create() *AircraftCreate {
	mutation := newAircraftMutation(c.config, OpCreate)
	return &AircraftCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Aircraft entities.
func (c *AircraftClient) CreateBulk(builders ...*AircraftCreate) *AircraftCreateBulk {
	return &AircraftCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Aircraft.
func (c *AircraftClient) Update() *AircraftUpdate {
	mutation := newAircraftMutation(c.config, OpUpdate)
	return &AircraftUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AircraftClient) UpdateOne(a *Aircraft) *AircraftUpdateOne {
	mutation := newAircraftMutation(c.config, OpUpdateOne, withAircraft(a))
	return &AircraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AircraftClient) UpdateOneID(id uuid.UUID) *AircraftUpdateOne {
	mutation := newAircraftMutation(c.config, OpUpdateOne, withAircraftID(id))
	return &AircraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Aircraft.
func (c *AircraftClient) Delete() *AircraftDelete {
	mutation := newAircraftMutation(c.config, OpDelete)
	return &AircraftDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AircraftClient) DeleteOne(a *Aircraft) *AircraftDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AircraftClient) DeleteOneID(id uuid.UUID) *AircraftDeleteOne {
	builder := c.Delete().Where(aircraft.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AircraftDeleteOne{builder}
}

// Query returns a query builder for Aircraft.
func (c *AircraftClient) Query() *AircraftQuery {
	return &AircraftQuery{
		config: c.config,
	}
}

// Get returns a Aircraft entity by its id.
func (c *AircraftClient) Get(ctx context.Context, id uuid.UUID) (*Aircraft, error) {
	return c.Query().Where(aircraft.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AircraftClient) GetX(ctx context.Context, id uuid.UUID) *Aircraft {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AircraftClient) Hooks() []Hook {
	return c.hooks.Aircraft
}
