// Code generated by entc, DO NOT EDIT.

package ent

import (
	"enttest/ent/aircraft"
	"enttest/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	aircraftFields := schema.Aircraft{}.Fields()
	_ = aircraftFields
	// aircraftDescCompanyID is the schema descriptor for company_id field.
	aircraftDescCompanyID := aircraftFields[1].Descriptor()
	// aircraft.DefaultCompanyID holds the default value on creation for the company_id field.
	aircraft.DefaultCompanyID = aircraftDescCompanyID.Default.(func() uuid.UUID)
	// aircraftDescID is the schema descriptor for id field.
	aircraftDescID := aircraftFields[0].Descriptor()
	// aircraft.DefaultID holds the default value on creation for the id field.
	aircraft.DefaultID = aircraftDescID.Default.(func() uuid.UUID)
}
